site_name: Model Modem
nav:
  - About: index.md
  - Development:
    - Cheat Codes: dev/cheat-codes.md
    - Git: dev/git/cheatsheet.md
    - Python: 
      - pip: dev/py/pip.md
    - PHP:
      - Official Docker: dev/php/official-docker.md
    - SQL:
      - SQL Server: dev/sql/sql-server.md
    - Docker:
      - Compose Specification: 
        - Spec: dev/docker/compose/spec.md
        - Build: dev/docker/compose/build.md
        - Deploy: dev/docker/compose/deploy.md
      - Configuration: dev/docker/config.md
    - Linux:
    #  - Bash:
    #    - Reference: dev/linux/bash/refs.md
      - Ubuntu: dev/linux/ubuntu/versions.md
    - MKDocs: dev/mkdocs.md
  - Technology:
    - My Stack: tech/my-stack.md


# Site Customizations
extra_css:
  - assets/css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js  # Sortable tables!
  - assets/js/extra.js
theme:
  name: material
  custom_dir: theme_overrides
  palette: 
    scheme: slate
  font:
    code: Fira Code
    text: Montserrat
  icon:
    logo: material/alpha-m-circle
    repo: fontawesome/brands/github-square
  features:
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
extra:
  disqus: modelmodem-com
  social: 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/djsipe/ 
repo_url: https://github.com/djsipe/model-modem
repo_name: Model Modem
markdown_extensions:
  - toc:
      permalink: ⚓︎
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.details
  - admonition
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg